package com.j_phone.io;

public interface StorageConnection extends javax.microedition.io.StreamConnection {
    public static final java.lang.String ROOT_INTERNAL = "/ms/";
    public static final java.lang.String ROOT_EXTERNAL = "/mc/";
    public static final int TYPE_FOLDER = 1;
    public static final int TYPE_ZIP = 2;
    public static final int TYPE_HTML = 3;
    public static final int TYPE_PNG = 4;
    public static final int TYPE_MNG = 5;
    public static final int TYPE_JPEG = 6;
    public static final int TYPE_SMAF = 7;
    public static final int TYPE_SMD = 8;
    public static final int TYPE_TXT = 9;
    public static final int TYPE_NANCY = 10;
    public static final int TYPE_VCARD = 11;
    public static final int TYPE_VBOOKMARK = 12;
    public static final int TYPE_VCALENDAR = 13;
    public static final int TYPE_VMESSAGE = 14;
    public static final int TYPE_VNOTE = 15;
    public static final int TYPE_EML = 16;
    public static final int TYPE_MPEG4 = 17;
    public static final int TYPE_OTHER = 18;
    public static final int TYPE_MP4 = 19;
    public static final int TYPE_GIF = 20;
    public static final int TYPE_SVG = 21;
    public static final int TYPE_SWF = 22;
    public static final int TYPE_AMR = 23;
    public static final int TYPE_MP3 = 24;
    public static final int TYPE_DCF = 25;
    public static final int TYPE_JAVA = 26;
    public static final int TYPE_PDF = 27;
    public static final int TYPE_WORD = 28;
    public static final int TYPE_EXCEL = 29;
    public static final int TYPE_POWERPOINT = 30;
    public static final java.lang.String ATTRIBUTE_NAME = "";
    public static final java.lang.String ATTRIBUTE_VENDOR = "";
    public static final java.lang.String ATTRIBUTE_VERSION = "";
    public static final java.lang.String ATTRIBUTE_DESCRIPTION = "";
    public static final java.lang.String ATTRIBUTE_CATEGORY = "";

    public boolean exists () throws java.io.IOException;
    public int getType () throws java.io.IOException;
    public java.lang.String getTypeString () throws java.io.IOException;
    public long getLength () throws java.io.IOException;
    public boolean isFolder () throws java.io.IOException;
    public boolean isFile () throws java.io.IOException;
    public boolean isCopyrighted () throws java.io.IOException;
    public int getCopyrightedDataVersion () throws java.io.IOException;
    public java.lang.String getCopyrightedDataContentType () throws java.io.IOException;
    public java.lang.String getCopyrightedDataHeader (java.lang.String name) throws java.io.IOException;
    public java.lang.String[] list () throws java.io.IOException;
    public boolean createFolder () throws java.io.IOException;
    public boolean renameTo (java.lang.String newName) throws java.io.IOException;
    public boolean delete () throws java.io.IOException;
    public void close () throws java.io.IOException;
    public java.io.InputStream openInputStream () throws java.io.IOException;
    public com.j_phone.io.InputRandomAccess openInputRandomAccess () throws java.io.IOException;
    public java.io.OutputStream openOutputStream () throws java.io.IOException;
    public java.lang.String getApplicationDescription (java.lang.String attribute) throws java.io.IOException;}
