package com.j_phone.io;

public interface StorageConnection extends javax.microedition.io.StreamConnection {
    public static final java.lang.String ROOT_INTERNAL = "";
    public static final java.lang.String ROOT_EXTERNAL = "";
    public static final int TYPE_FOLDER = 0;
    public static final int TYPE_ZIP = 0;
    public static final int TYPE_HTML = 0;
    public static final int TYPE_PNG = 0;
    public static final int TYPE_MNG = 0;
    public static final int TYPE_JPEG = 0;
    public static final int TYPE_SMAF = 0;
    public static final int TYPE_SMD = 0;
    public static final int TYPE_TXT = 0;
    public static final int TYPE_NANCY = 0;
    public static final int TYPE_VCARD = 0;
    public static final int TYPE_VBOOKMARK = 0;
    public static final int TYPE_VCALENDAR = 0;
    public static final int TYPE_VMESSAGE = 0;
    public static final int TYPE_VNOTE = 0;
    public static final int TYPE_EML = 0;
    public static final int TYPE_MPEG4 = 0;
    public static final int TYPE_OTHER = 0;
    public static final int TYPE_MP4 = 0;
    public static final int TYPE_GIF = 0;
    public static final int TYPE_SVG = 0;
    public static final int TYPE_SWF = 0;
    public static final int TYPE_AMR = 0;
    public static final int TYPE_MP3 = 0;
    public static final int TYPE_DCF = 0;
    public static final int TYPE_JAVA = 0;
    public static final int TYPE_PDF = 0;
    public static final int TYPE_WORD = 0;
    public static final int TYPE_EXCEL = 0;
    public static final int TYPE_POWERPOINT = 0;
    public static final java.lang.String ATTRIBUTE_NAME = "";
    public static final java.lang.String ATTRIBUTE_VENDOR = "";
    public static final java.lang.String ATTRIBUTE_VERSION = "";
    public static final java.lang.String ATTRIBUTE_DESCRIPTION = "";
    public static final java.lang.String ATTRIBUTE_CATEGORY = "";

    public boolean exists () throws java.io.IOException;
    public int getType () throws java.io.IOException;
    public java.lang.String getTypeString () throws java.io.IOException;
    public long getLength () throws java.io.IOException;
    public boolean isFolder () throws java.io.IOException;
    public boolean isFile () throws java.io.IOException;
    public boolean isCopyrighted () throws java.io.IOException;
    public int getCopyrightedDataVersion () throws java.io.IOException;
    public java.lang.String getCopyrightedDataContentType () throws java.io.IOException;
    public java.lang.String getCopyrightedDataHeader (java.lang.String name) throws java.io.IOException;
    public java.lang.String[] list () throws java.io.IOException;
    public boolean createFolder () throws java.io.IOException;
    public boolean renameTo (java.lang.String newName) throws java.io.IOException;
    public boolean delete () throws java.io.IOException;
    public void close () throws java.io.IOException;
    public java.io.InputStream openInputStream () throws java.io.IOException;
    public com.j_phone.io.InputRandomAccess openInputRandomAccess () throws java.io.IOException;
    public java.io.OutputStream openOutputStream () throws java.io.IOException;
    public java.lang.String getApplicationDescription (java.lang.String attribute) throws java.io.IOException;}
